name: CI/CD Pipeline with OWASP ZAP Security Scan

on:
  push:
    branches:
      - main  # Trigger when pushing to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger when creating a pull request for the 'main' branch

jobs:
  security-scan:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up OWASP ZAP Docker container (in headless mode)
      - name: Set up OWASP ZAP for Dynamic Security Testing
        uses: docker://owasp/zap2docker-stable:latest
        with:
          entrypoint: "/bin/bash"
          args: "-c 'zap-cli quick-scan --self-contained -t http://localhost:8080'"

      # Start OWASP ZAP in headless mode (no UI)
      - name: Run OWASP ZAP Security Scan
        run: |
          docker run -t owasp/zap2docker-stable -t http://localhost:8080 -g gen.conf -r zap_report.html

      # Upload the ZAP report to GitHub artifacts
      - name: Upload ZAP Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html  # Path to the report generated by ZAP
