name: CI/CD Pipeline with OWASP ZAP Security Scan

on:
  push:
    branches:
      - master  # Trigger when pushing to the 'master' branch
  pull_request:
    branches:
      - master  # Trigger when creating a pull request for the 'master' branch

jobs:
  security-scan:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up OWASP ZAP and run the security scan
      - name: Run OWASP ZAP Security Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'http://localhost:8080'  # Target URL for the scan
          docker_image: 'owasp/zap2docker-stable:latest'  # Optional: you can specify the image for internal use
          rules_file: 'zap_rules.txt'  # Optional: if you want to provide custom scan rules
          api_key: ${{ secrets.ZAP_API_KEY }}  # Optional: if you need an API key for OWASP ZAP

      # Upload the ZAP report to GitHub artifacts
      - name: Upload ZAP Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html  # Path to the report generated by ZAP
